server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
spring:
  application:
    name: springcloud-feign

  thymeleaf:
    encoding: UTF-8
    servlet:
      content-type: text/html
